//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaDoZeProj.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzariaDoZeProj.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrir Aplicação.
        /// </summary>
        internal static string AbrirAplicacao {
            get {
                return ResourceManager.GetString("AbrirAplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clientes.
        /// </summary>
        internal static string ButtonClientes {
            get {
                return ResourceManager.GetString("ButtonClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string buttonConfiguracoes_Text {
            get {
                return ResourceManager.GetString("buttonConfiguracoes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Continuar.
        /// </summary>
        internal static string buttonContinuar {
            get {
                return ResourceManager.GetString("buttonContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string buttonEditar {
            get {
                return ResourceManager.GetString("buttonEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço.
        /// </summary>
        internal static string ButtonEndereco {
            get {
                return ResourceManager.GetString("ButtonEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string buttonExcluir {
            get {
                return ResourceManager.GetString("buttonExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionários.
        /// </summary>
        internal static string ButtonFuncionarios {
            get {
                return ResourceManager.GetString("ButtonFuncionarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes.
        /// </summary>
        internal static string ButtonIngredientes {
            get {
                return ResourceManager.GetString("ButtonIngredientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Minimizar.
        /// </summary>
        internal static string buttonMinimizar {
            get {
                return ResourceManager.GetString("buttonMinimizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produtos.
        /// </summary>
        internal static string ButtonProdutos {
            get {
                return ResourceManager.GetString("ButtonProdutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabores.
        /// </summary>
        internal static string ButtonSabores {
            get {
                return ResourceManager.GetString("ButtonSabores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        internal static string buttonSair {
            get {
                return ResourceManager.GetString("buttonSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string buttonSalvar {
            get {
                return ResourceManager.GetString("buttonSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valores Pizza:.
        /// </summary>
        internal static string ButtonValores {
            get {
                return ResourceManager.GetString("ButtonValores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Encerrar.
        /// </summary>
        internal static string Encerrar {
            get {
                return ResourceManager.GetString("Encerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro:.
        /// </summary>
        internal static string LabelBairro_Text {
            get {
                return ResourceManager.GetString("LabelBairro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria:.
        /// </summary>
        internal static string labelCategoria_Text {
            get {
                return ResourceManager.GetString("labelCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP:.
        /// </summary>
        internal static string LabelCEP_Text {
            get {
                return ResourceManager.GetString("LabelCEP.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade:.
        /// </summary>
        internal static string LabelCidade_Text {
            get {
                return ResourceManager.GetString("LabelCidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Clientes:.
        /// </summary>
        internal static string labelClientes_Text {
            get {
                return ResourceManager.GetString("labelClientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNH:.
        /// </summary>
        internal static string labelCNH_Text {
            get {
                return ResourceManager.GetString("labelCNH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento:.
        /// </summary>
        internal static string labelComplemento_Text {
            get {
                return ResourceManager.GetString("labelComplemento.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF:.
        /// </summary>
        internal static string labelCPF_Text {
            get {
                return ResourceManager.GetString("labelCPF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email:.
        /// </summary>
        internal static string labelEmail_Text {
            get {
                return ResourceManager.GetString("labelEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado:.
        /// </summary>
        internal static string LabelEstado_Text {
            get {
                return ResourceManager.GetString("LabelEstado.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foto:.
        /// </summary>
        internal static string labelFoto_Text {
            get {
                return ResourceManager.GetString("labelFoto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Funcionáros:.
        /// </summary>
        internal static string labelFuncionarios_Text {
            get {
                return ResourceManager.GetString("labelFuncionarios.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo:.
        /// </summary>
        internal static string labelGrupo_Text {
            get {
                return ResourceManager.GetString("labelGrupo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID:.
        /// </summary>
        internal static string LabelID_Text {
            get {
                return ResourceManager.GetString("LabelID.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Ingredientes:.
        /// </summary>
        internal static string labelIngredientes_Text {
            get {
                return ResourceManager.GetString("labelIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes:.
        /// </summary>
        internal static string LabelListaIngredientes_Text {
            get {
                return ResourceManager.GetString("LabelListaIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro:.
        /// </summary>
        internal static string LabelLogradouro_Text {
            get {
                return ResourceManager.GetString("LabelLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matrícula:.
        /// </summary>
        internal static string LabelMatricula_Text {
            get {
                return ResourceManager.GetString("LabelMatricula.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ML:.
        /// </summary>
        internal static string labelML_Text {
            get {
                return ResourceManager.GetString("labelML.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome:.
        /// </summary>
        internal static string labelNome_Text {
            get {
                return ResourceManager.GetString("labelNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número:.
        /// </summary>
        internal static string labelNumero_Text {
            get {
                return ResourceManager.GetString("labelNumero.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observação:.
        /// </summary>
        internal static string labelObservacao_Text {
            get {
                return ResourceManager.GetString("labelObservacao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a País:.
        /// </summary>
        internal static string LabelPais_Text {
            get {
                return ResourceManager.GetString("LabelPais.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Produtos:.
        /// </summary>
        internal static string labelProdutos_Text {
            get {
                return ResourceManager.GetString("labelProdutos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Sabores:.
        /// </summary>
        internal static string labelSabores_Text {
            get {
                return ResourceManager.GetString("labelSabores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha:.
        /// </summary>
        internal static string labelSenha_Text {
            get {
                return ResourceManager.GetString("labelSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho:.
        /// </summary>
        internal static string labelTamanho_Text {
            get {
                return ResourceManager.GetString("labelTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone:.
        /// </summary>
        internal static string labelTelefone_Text {
            get {
                return ResourceManager.GetString("labelTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tem Certeza?.
        /// </summary>
        internal static string labelTemCerteza_Text {
            get {
                return ResourceManager.GetString("labelTemCerteza.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo:.
        /// </summary>
        internal static string labelTipo_Text {
            get {
                return ResourceManager.GetString("labelTipo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        internal static string labelUsuario_Text {
            get {
                return ResourceManager.GetString("labelUsuario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validade:.
        /// </summary>
        internal static string labelValidade_Text {
            get {
                return ResourceManager.GetString("labelValidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor:.
        /// </summary>
        internal static string labelValor_Text {
            get {
                return ResourceManager.GetString("labelValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor Adicional Borda:.
        /// </summary>
        internal static string labelValorBorda_Text {
            get {
                return ResourceManager.GetString("labelValorBorda.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Valores:.
        /// </summary>
        internal static string labelValores_Text {
            get {
                return ResourceManager.GetString("labelValores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logopizzaria {
            get {
                object obj = ResourceManager.GetObject("logopizzaria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Administrador.
        /// </summary>
        internal static string radioButtonAdministrador_Text {
            get {
                return ResourceManager.GetString("radioButtonAdministrador.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atendente.
        /// </summary>
        internal static string radioButtonAtendente_Text {
            get {
                return ResourceManager.GetString("radioButtonAtendente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entregador.
        /// </summary>
        internal static string radioButtonEntregador_Text {
            get {
                return ResourceManager.GetString("radioButtonEntregador.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string Sobre {
            get {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }
    }
}
